spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:mysql://localhost/auth?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    org:
      springframework:
        security: TRACE